// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	// Должен быть предъявлен при запросе токена пользователя
	// Получаем в ответе на GET запрос формы авторизации
	//
	// Отправляем в HTTP заголовке Client-ID
	ClientID string `json:"client_id"`
	// Должен быть предъявлен при запросе токена пользователя
	// Получаем в ответе на GET запрос формы авторизации
	//
	// Отправляем в HTTP заголовке Authorization
	Token string `json:"token"`
	// Указывает на наличие авторизации
	Authorized bool `json:"authorized"`
	// Метод авторизации
	Method string `json:"method"`
}

type Session struct {
	Sid string `json:"sid"`
	// Флаг наличия websocket соединения
	Online bool `json:"online"`
	// Токен авторизации, должен совпасть с тем
	// что отдали клиенту при отправке формы авторизации
	AuthToken string `json:"auth_token"`
	// Идентификатор пользователя
	UID int `json:"uid"`
	// Метод авторизации установленный пользователем
	Method string `json:"method"`
}

type User struct {
	UID      int    `json:"uid"`
	Username string `json:"username"`
	Active   bool   `json:"active"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Method   string `json:"method"`
}
